#!/bin/sh

# start with an empty plugin subfolder
rm -rf plugin
mkdir -p plugin

# copy the hello-login plugin files into plugin folder
cp -v ../CHANGELOG.md ../hello-login.php ../readme.txt plugin/
cp -r -v ../css ../includes ../languages plugin/

# start the docker containers, plugin subfolder is bound inside WordPress container
docker-compose up -d

# wait for the WordPress service to start
sleep 10s

# open WordPress in browser
open http://localhost:8080/
