name: PR Unit Testing

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on pull request events
  pull_request:

env:
  ACTION_VERSION: 3

jobs:
  pr_unit_testing:
    runs-on: ubuntu-latest

    name: 'Unit Test PR in Latest Stable Requirements'

    steps:
    - name: Checkout Code
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Start Docker Environment
      run: docker compose up -d

    - name: Run PHPUnit Tests
      run: docker compose exec app /bin/bash -c 'composer install && composer phpunit'

    - name: Shutdown Docker Environment
      if: success() || failure()
      run: docker compose down

    - name: Generate Coverage Report
      if: success()
      # https://github.com/marketplace/actions/coverage-report-as-comment-clover
      uses: lucassabreu/comment-coverage-clover@main
      with:
        file: clover.xml

